area: # has special handling with 'knowledge' abilities
  cone:
    medium: 2
    large: 5
    detection: 1  # standard 50' detection cone is cheap (SR offset)
  cylinder:
    small: 2
    medium: 4
    large: 6
  line:
    small: 1
    medium: 2
    large: 4 # 50 x 10
    huge: 5 # 100 x 10
    gargantuan: 6 # 100 x 20
  radius:
    small: 2
    medium: 4
    large: 6
    huge: 7 # 100' radius
    gargantuan: 8 # 200' radius
    colossal: 9 # 500' radius
    mile: 10
  wall:
    medium: 2
    large: 3
    huge: 4 # 100'
# different area types have special modifiers
area type:
  burst: 0
  emanation: -1
  limit: 0
  zone: -2
battlefield effects:
  balance to move: 3
  cover: 1 # usually by walls
  damage: 4
  difficult terrain: 1
  fog: 1
  impassable: 6 # for walls
  light: 1
  prismatic: 5
  underwater penalties: 3
  underwater: 5
  weak damage: 1 # like wall of thorns
breakable:
  combat: -2 # if you engage in combat against the target
  easy damage reduction: -1 # like bludgeoning, piercing, slashing, fire
  deal energy damage: -1 # like wall of fire
  deal physical damage: -1 # like crushing hand
  grapple: -1
  if attack: -5
  if attack per round: -2
  if damaged: -3
  maze: -1
  standard skill check: -3
  standard action by any: -2
  standard action by target: -3
  specific spell: -1 # remove curse, etc. Not for use on spells with less than one month of duration
  violent action by any: -3
buffs:
  all attributes:
    plus2: 7
    plus4: 10
  all skills:
    mastery: 5
    plus5: 6 # same cost as 5 skills
    plus10: 9 # same cost as 5 skills
  attribute:
    plus2: 3
    plus4: 6
  physical attributes:
    plus2: 5
    plus4: 8
  mental attributes:
    plus2: 5
    plus4: 8
  alter weapon: 1
  amorphous: 5
  attack special defense - half: 5
  attack special defense: 8
  blindsense: 3
  blindsight: 6
  climb speed: 2
  cover miss physical: 4
  # make sure these don't stack well with other crit range bonuses
  critical multiplier: 4
  critical range: 4
  critical immunity: 2
  darkvision: 1
  damage immunity:
    single fixed: 2
    single choice: 5
  damage reduction:
    arcane: 2
    energy all: 3
    energy single: 1
    physical half: 1
    physical: 4
    single: 1
    spell: 3
    alignment: 3
    all: 5
  double dr:
    energy all: 5
    energy single: 3
    physical: 8
    single: 5
    spell: 7
    alignment: 7
    all: 9
  double range: 1  # for ranged weapons
  deal half damage to allies: 3  # affects all of target's abilities
  deal no damage to allies: 6  # affects all of target's abilities
  defense:  # for class features, not spells!
    plus2: 2
    plus5: 5
  delay damage: 5
  disguise: 3
  double speed: 3
  finesse weapon: 1
  quadruple speed: 6
  earth glide: 7
  earthen blade: 1
  ethereal: 9
  extra attack: 8
  extra attack with penalty: 4 # at -5 attack bonus
  fast healing: 5
  feat:  # the cost depends on the minimum level the feat could be gained
    level1: 2
    level5: 4
    level10: 6
  flame blade: 3
  flight: 7
  foresee probability: 3
  gaseous form: 6
  glide: 3
  half critical damage: 2  # take half normal critical damage
  half miss all: 10
  half miss physical: 7
  half miss ranged: 4
  heal critical: 4  # heal critical as easily as hp
  hide attack effects: 1
  ignore minor miss chance: 3
  increase overwhelm: 3
  increase size: 5 # mix of upsides and downsides
  increase effective size: 4 # as larger than life
  increase weapon size: 2
  invisible: 10
  ignore concealment: 2 # but not total concealment
  ignore damage reduction: 3  # equal to spellpower
  ignore hardness: 2  # equal to half spellpower
  ignore threatened terrain: 1
  immune:
    compulsion: 1
    construct: 8
    critical damage: 12  # it's immortality...
    critical hits: 2
    death: 1
    delusion: 1
    falling damage: 1
    grapple: 2
    mind: 6
    movement effects: 1
    poison: 2
    regeneration: 5
    unaware: 3
    underwater: 1
  legend point:
    all: 3
    defensive: 2
    physical: 2
    offensive: 2
  legend point regeneration:
    round: 5
    short: 2
    medium: 1
    # any longer delay is pointless
  levitation: 5
  lifesight: 6
  low light vision: 1
  mage armor: 2 # a bit low, but mage armor is special
  maneuver accuracy: # plus5
    all: 4  # plus5, all maneuvers
    one: 2
  maneuver defense: 3  # plus5
  move through foes: 2
  natural grab: 4
  natural poison: 4
  natural shove: 2
  natural trip: 4
  natural weapon: 1
  nondetection: 2
  one attack misses: 8  # per round; as Reflexive Dodge
  radiate light: 0
  rage bonus plus2: 8
  ranged melee weapon:
    close: 2
    medium: 3
    long: 4
  reduce overwhelm:
    by five: 5
  reduce encumbrance:
    2: 2
    4: 3
    6: 4
  reduce size: 4
  reroll random effects: 3
  retributive damage:
    melee: 4
    close: 5
    medium: 5.5
    long: 6
    extreme: 6.5
  scent: 3
  see invisibility: 3
  shadow duplicate: 8
  share pain: 3
  share pain selective: 7
  shield of faith: 3
  skill:
    class skills: 1  # up to two class skills
    extra mastery: 1
    extra plus5: 1
    extra plus10: 1
    mastery: 1  # roll twice
    skill point: 1  # only for class features, obviously
    plus2 attribute: 2  # all skills from an attribute
    plus5: 2
    plus10: 5
  spellsight: 6  # worse than blindsight, but spell info balances
  swim speed: 1
  spell resistance limited: 3
  spell resistance: 5
  target reflex: 4  # attacks target lower of armor and reflex
  telepathy: 6
  temporary hp: 3  # lower than dr, but no stacking and smaller total "healing"
  ten foot speed: 2
  time stop: 14
  tremorsense: 3  # 50' range
  true seeing: 9
  unapproachable: 7
  unarmed warrior: 2
  undead: 1
  walking flight: 7
  wary rage: 2
  water breathing: 3
  water speaking: 1
  water walk: 2
  weapon enhancement: 3  # to be level-appropriate
  weapon proficiency: 0
  weapon reach: 2
  weapon reach - ten: 4
  win initiative: 6
  woodland stride: 1
  free augment, limited: 3
  free augment: 6
  defense bonus:
    1: 3
    2: 5
casting time:
  immediate: 4
  personal move: 2 # only very few spells should be move - stuff like teleportation
  move: 2
  standard: 0
  swift: 4
  # the casting time is somewhat offset by the double roll
  strike feat: 4
  on hit: 3
choose effect:
  true: 1
  false: 0
components:
  all: 0
  none: 2
  nosomatic: 1
  noverbal: 1
conditions:
  # simple conditions with only minor downsides
  faerie fire: 1
  fatigued: 2
  gender swap: 2 # this should only be accessible by high level, but doesn't do much
  half speed: 1
  lower max hp: 1
  reduce hardness: 1  # by spellpower
  sickened: 1
  # lose ability to take less important actions
  # or low probability of losing important actions
  shaken: 2
  goaded: 2  # like impaired, but weaker
  crouching: 3
  deafened: 3
  die from critical: 3 # die from taking critical damage at 0 HP
  dimension lock: 3
  forget: 3
  quarter speed: 3
  ignited: 3 # implied removal mechanics
  impaired: 3
  reduce damage reduction: 3  # by spellpower
  silenced: 3
  target reflex: 4  # attacks target lower of armor and reflex
  partially blinded: 4 # +1 for removing special vision
  no zero threshold: 4
  # lose ability to take a subset of "real" actions
  dazed: 6
  die at zero: 6
  disoriented: 6
  entangled: 5 # impaired + fatigued
  exhausted: 5 # impaired + fatigued
  fascinated: 6
  immobilized: 6
  slowed: 6
  staggered: 6
  taunted: 7
  frightened: 8
  # significant reduction in ability to act
  # but can still try to do things normally, mostly
  aversion: 8 # conditional severe impairment, but often better
  charmed: 9 # weird - how does interact with combat?
  command movement: 9 # like staggered, but worse
  no violence: 9
  out of battle: 9
  severely impaired: 9
  stasis: 9
  suggestion: 9 # like aversion, but more flexible
  super silenced: 9
  take double physical damage: 9
  take double damage: 11
  # can take only a small subset of actions with any success
  # or can only act normally with small probability
  blinded: 11  # some actions are totally unpenalized
  antimagic: 12
  confused: 12
  feeblemind: 12
  grappled: 12
  panicked: 13
  # can take no actions
  command full movement: 16 # slightly better than no actions
  nauseated: 15
  paralyzed: 15 # mental actions offset coup de grace
  stunned: 15
  # even worse than unable to act
  asleep: 18 # if can be woken, use "breakable"
  dominated: 18
damage:
  critical overbleed: 5
  double: 5 # only for use with critical effects
  # "double" damage should STACK with "normal" damage; the total cost is 8
  physical attack: 1
  empowered: 7
  healing: 3
  normal: 3
  kill at zero: 7
  # do not confuse DOT effects with battlefield effect: damage
  over time: 3
  cantrip: 1
delay effect:  # for offensive spells only
  round: -1
  short: -3
  medium: -3.5
  long: -4
duration:
  condition:
    round: -1
    concentration: 0
    brief: 0 # 2 rounds
    until standard action: 1
    short fixed: 2
    medium: 3 # x10
    disease: 3
    long: 3.5 # x6
    extreme: 4 # x12
    week: 5 # x14
    month: 5.5 # x4
    year: 6 # x12
    created: 6
    permanent: 7 # x???
  battlefield effect:
    round: -3
    concentration: -2
    brief: -2
    short fixed: 0
    short: 0
    medium: 1
    long: 1.5
    extreme: 2
    week: 3
    month: 3.5
    year: 4
    created: 4
    permanent: 5
    class feature: 4
    passive ability: 5
  personal buff:
    end of round: -2  # for immediate/swift
    round: -2
    concentration: -1
    brief: -1
    short fixed: 0
    short: 1
    medium: 3
    long: 4
    extreme: 5
    # rituals only
    week: 6
    month: 6.5
    year: 7
    permanent: 8
    class feature: 4
    passive ability: 5
    # activated class feature: 3
  nonpersonal buff:
    end of round: -2  # for immediate/swift
    round: -2
    concentration: -1
    short fixed: 0
    short: 1
    # actually making it long requires +2 spell levels
    # all 'personal long' spells should be close range
    # because you don't benefit from close range when casting it on yourself
    personal long: 1
    medium: 6
    long: 7
    extreme: 8
    week: 9
    month: 9.5
    year: 10
    permanent: 11
    # match cost of long duration personal-only buff
    class feature: 4
    passive ability: 5
    # class features where you can only have one of multiple choices
    class feature choice: 3
  noncombat buff:
    end of round: -2  # for immediate/swift
    round: -2
    concentration: -1
    short fixed: 0
    short: 1
    personal long: 1
    medium: 3
    long: 4
    extreme: 5
    # rituals only
    week: 6
    month: 6.5
    year: 7
    permanent: 8
    class feature: 3
    passive ability: 3
expended:
  single use: -3
  five: -2 # or other values between single use and caster level
  caster level: -1
healing:
  normal: 3
  fast healing: 5
  critical overbleed:
    10: 4
    5: 5
    2: 6
    full: 8
instant effect:
  banishment: 14
  critical damage: 8 # one critical damage
  death: 18
  dispel: 7
  negative levels: 7 # one negative level per two spell levels
  full negative levels: 14 # one negative level per spell level
  maneuver: 3 # +spellpower
  resurrect: 9  # recently deceased only, for world continuity
  nothing: 0
  shove: 1 # +spellpower; one of the weaker maneuvers
  prismatic: 5
  prone: 2
  remove heal conditions: 4
  remove physical conditions: 3
knowledge:
  alignment: 3
  creature or object location: 4
  creature location: 3
  object location: 2
  lies: 4
  thoughts: 8
  vulnerabilities: 1
limit affected:
  normal:
    alignment: -2
    creature type: -2
    language: -2
    willing: -2
    max size: -1
    mind affecting: -1
    nonalignment: -1
    near ground: -1 # within 10 feet of the ground
    on stone: -1
    near plants: -2 # within 5 feet of plants
    touching metal: -2
    light vulnerable: -6
  buff:
    alignment: -1
    creature type: -1
    falling: -4
    max size: 0
    mind affecting: 0
    nonalignment: -0.5
    near ground: -0.5 # within 10 feet of the ground
    on ground: -0.5
range:
  normal:
    personal: -1
    touch: 0
    close: 1
    medium: 2
    long: 3
    extreme: 4
  buff:
    personal: -1
    touch: 0
    close: 1
    medium: 1.5
    long: 2
    extreme: 2.5
repeatable:
  frequency:
    at will: 1
    short: 0
  duration:
    short fixed: 0
    short: 0
    medium: 1
    long: 2
    extreme: 3
    class feature: 3
  immediate: # takes effect immediately, in addition to later repeats
    true: 0  # not prebuffing makes this not significantly more powerful
      # because you're using a combat action for a lower-level effect
    false: 0
retry failure:
  true: 1
  false: 0
shadow: # subtle for spells that would normally have visual cues
  true: 1
  false: 0
shapeable:
  true: 1
  false: 0
spell resistance:
  true: 0
  false: 1
targets:
  area:
    all: 0
    five: -1
    enemies: 1
    allies: 0 # custom logic with buffs
    automatically find one: ~ # custom logic
  battlefield effect:
    all: 0
    enemies: 1
  normal:
    one: 0
    five: 3
    automatically find one: ~ # custom logic
teleport:
  range:
    close: 0
    medium: 1
    long: 2
    extreme: 3
  type:
    line of effect: 2
    unrestricted: 5
  willing:  # forced movement is significantly better on foes
    true: 0
    false: 2
trigger:
  condition:
    battlefield effect: 4 # the effect triggers every round in the area, like a battlefield effect
    every round: 4 # requires duration, assumes effects don't stack
    every round stacking: 6 # requires duration
    damage every round: 2 # cost shouldn't stack with damage, since damage is reduced
    # damage every round has unique damage scaling; if inescapable, it's
    # spellpower. If AOE escapable, there is a -1 die size penalty.
    enter zone: 1
    kill foe: 2
    on attack: 3  # takes effect when the target attacks
    standard action by any: 3
    standard action by you: 2
    when attacked: 2  # takes effect when the target is attacked
  duration:
    concentration: 0 # part of "standard action by you"
    short fixed: 0
    short: 0
    medium: 1 # x10
    long: 1.5 # x6
    extreme: 2 # x12
    week: 3 # x14
    month: 3.5 # x4
    year: 4 # x12
    permanent: 6 # x???
    class feature: 4
# damage die rules
# base: d10 per 2 spellpower
# save half: +1 die size
# save negates: +2 die size
# AOE: -2 die size
# AOE battlefield effect (brief): -3 die size
# AOE battlefield effect (short+): -4 die size
