---
default properties:
  casting time: standard
  components: all
  dispellable: true
  range: touch
  spell resistance: true
  targets: one
meta properties:
  - skip validation
primary properties:
  - attack subeffects
  - battlefield effects
  - buffs
  - conditions
  - damage
  - knowledge
  - healing
  - instant effect
  - subeffects
  - teleport
possible properties:
  - attack subeffects
  - area
  - battlefield effects
  - breakable
  - buffs
  - casting time
  - choose effect
  - components
  - conditions
  - damage
  - delay effect
  - dispellable
  - duration
  - expended
  - healing
  - instant effect
  - knowledge
  - limit affected
  - misc
  - noncombat
  - range
  - repeatable
  - shadow
  - shapeable
  - skip validation
  - spell resistance
  - subeffects
  - retry failure
  - targets
  - teleport
  - trigger
recursive properties:
  - subeffects
required properties:
  - range
  - targets
