default properties:
  size: medium
meta properties:
  - level
  - race
  - rise class
  - skip validation
  - special attack name
  # these are not meta properties, but are here for testing
  - armor
  - feats
  - templates
possible properties:
  - attributes
  - speeds
  - spells
  - size
  - traits
  - weapons
required properties:
  - size
